// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QRSCAN.Data;

#nullable disable

namespace QRSCAN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QRSCAN.Models.Entities.BanAn", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NoiDungQR")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SoChoNgoi")
                        .HasColumnType("int");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaBan");

                    b.ToTable("BanAns");
                });

            modelBuilder.Entity("QRSCAN.Models.Entities.PhienGoiMon", b =>
                {
                    b.Property<int>("MaPhien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("KetThuc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaBan")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaPhien");

                    b.HasIndex("MaBan");

                    b.ToTable("PhienGoiMons");
                });

            modelBuilder.Entity("QRSCAN.Models.Entities.PhienGoiMon", b =>
                {
                    b.HasOne("QRSCAN.Models.Entities.BanAn", "BanAn")
                        .WithMany("PhienGoiMons")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BanAn");
                });

            modelBuilder.Entity("QRSCAN.Models.Entities.BanAn", b =>
                {
                    b.Navigation("PhienGoiMons");
                });
#pragma warning restore 612, 618
        }
    }
}
